### ISSUE TITLE
Unable to resolve action `vio/bundle-stats-action@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by alexcroox** [vio/bundle-stats-action#49]
Following the README:

```
- name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: 'dist/stats.json'
```

Unable to resolve action `vio/bundle-stats-action@v1`, unable to find version `v1`
