### ISSUE TITLE
Invalid webpack stats structure, please make sure webpack stats configuration is correct.

### ISSUE THREAD

**Issue by eloisetaylor5693** [vio/bundle-stats-action#91]
Get this error when using the github action task

## Error:
```
Run vio/bundle-stats-action@v1.3.0
  with:
    webpack-stats-path: public/webpack.stats.json
Warning: Invalid webpack stats structure, please make sure webpack stats configuration is correct.

Expected a value of type `interface<{name,size}> | interface<{type,filteredChildren,size}>[] & notEmptyArray` for `assets`
```

## Github action 
```yaml
...
    - run: npm ci
    - run: npm run build 
    
    - run: cat public/webpack.stats.json  #<--- shows expected output
    
    - name: BundleStats
      with:
        webpack-stats-path: public/webpack.stats.json
```

## Local config
` "gatsby-plugin-bundle-stats": "^3.1.3",`

`gatsby,config`:
```javascript
module.exports = {
     ....
     plugins: [
     ....
          `gatsby-plugin-bundle-stats`,
     ]
}
```
